# Site settings
title: Manjot Nagyal
email: your-email@domain.com
url: "https://manjot-nagyal.github.io/manjot-nagyal"
# url: "manjotnagyal.com"
# baseurl: "/manjot-nagyal" # the subpath of your site, e.g. /blog
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: ""
meta_author: Nagyal Manjot

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 132454 #DEDEF6 #18bc9c #80B3FF
  primary-rgb: "244,96,54" #"24,288,156" #"128,179,255"
  secondary: 132454 #2c3e50 #FD6E8A
  secondary-dark: FA3A00 #A2122F

# Footer settings
footer:
  copyright: Manjot Nagyal
  # location: Location
  # social: Around the Web
  # credits: Adapted from Freelancer Jekyll theme

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/manjot-nagyal
  - title: github
    url: https://github.com/manjot-nagyal

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
